language: en
pipeline:
- name: SpacyNLP
- name: SpacyTokenizer
- name: SpacyFeaturizer
- name: RegexFeaturizer
- name: CRFEntityExtractor
- name: EntitySynonymMapper
- name: SklearnIntentClassifier
- name: ResponseSelector

policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: MappingPolicy
